version: '3.8'

services:
  postgres:
    image: "postgres:11-alpine"
    ports:
      - 5432:5432
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U billing"]
      interval: 10s
      timeout: 5s
      retries: 3

  back:
    build:
      context: .
    env_file:
      - .env